# Generated by Django 4.1.4 on 2022-12-25 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
    ]
